pipeline {
    agent any
    tools{
        nodejs 'node'
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'rm -rf Projects-React'
                sh 'git clone https://github.com/a22939sv/Projects-React.git'
                sh 'cd Projects-React/react-front-app && npm install'
            }
        }
        stage('Test') {
            steps {
                //sh './Projects-React/react-front-app/jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh 'cd Projects-React/react-front-app && npm start'
                //sh './Projects-React/react-front-app/jenkins/scripts/deliver.sh'
                //input message: 'Finished using the web site? (Click "Proceed" to continue)'
                //sh './Projects-React/react-front-app/jenkins/scripts/kill.sh'
            }
        }
    }
}
